#!/bin/bash

######################################################
### Interpolate original aerosol files to new grid ###
######################################################

# Mickaël LALANDE (mickael.lalande@univ-grenoble-alpes.fr)
# 06/02/2020
# Adapted from Olivier Boucher?

# The path needs to be changed + the years in the loop at the end

# Make crash the script if one command does not work
# https://stackoverflow.com/questions/2870992/automatic-exit-from-bash-shell-script-on-error
# Prevent to regrid the files in wrong directory (ex: if cd does not work)
set -e

experiment=ELI-144x142x79-zoomx2-himalaya-test
path=$STORE/IGCM_OUT/LMDZ/$experiment/ATM/Output
ozone_path=/gpfswork/rech/psl/commun/IGCM/ATM/AEROSOLS/CMIP6/v1/144x142/L79
# Grid file generated by CREATE_amip
gridfile=$path/Grid/${experiment}_1979_grilles_gcm.nc

echo "--------------------------------------------------------------------------------"
echo " * Experiment: $experiment"
echo " * Orignal ozone path: $ozone_path"
echo " * Grid file: $gridfile"
echo "--------------------------------------------------------------------------------"

# Get into the Boundary folder
echo " -> Get into $path/Boundary"
cd $path/Boundary

# Extraction d'un fichier de grille physique a partir de grilles_gcm.nc
if ! [ -e grille_phys.nc ]
then
	if ! [ -e grilles_gcm.nc ]
	then
		echo " - Copy the ${gridfile} to grilles_gcm.nc"
		cp ${gridfile} grilles_gcm.nc
	fi

	echo " - Make a physical grid from grilles_gcm.nc"	
	imp1=`ncdump -h grilles_gcm.nc | grep lonv | head -1 | awk ' { print $3 } '`
	echo " - lonv = $imp1"
	(( imm1 = $imp1 - 2 ))
	echo " - lon = $imm1"
	ncks -d lonv,0,$imm1 grilles_gcm.nc -v phis -O grille_phys.nc
	ncrename -v lonv,lon -v latu,lat -d lonv,lon -d latu,lat -O grille_phys.nc
	ncap2 -s "lon=-360.+lon" grille_phys.nc -O tmp.nc
	\mv -f tmp.nc grille_phys.nc
	echo " + grille_phys.nc generated"
else
	echo " = The file grille_phys.nc already exist"
fi

# Regrid over years + 1850 (aerosols.nat.nc) using CDO conservative method
for year in 1850 {1979..1980} 
do
	if ! [ -e aerosols${year}_from_inca.nc ]
	then
		cdo remapcon,grille_phys.nc $ozone_path/aerosols${year}_from_inca.nc aerosols${year}_from_inca.nc
		echo " + aerosols${year}_from_inca.nc generated"
	else
		echo " = aerosols${year}_from_inca.nc already exist"
	fi
done

